export const CONVERTER_CREDIT_PACKS = [
  {
    id: 'starter',
    name: 'Starter',
    credits: 3,
    price: '$3.99',
    perCredit: '$1.33 each',
    save: 'Save 11%',
    description: '3 downloads of any size. Good for a one-off project.',
    cta: 'Choose Starter',
    variant: 'outline',
  },
  {
    id: 'pro',
    name: 'Pro',
    credits: 5,
    price: '$5.99',
    perCredit: '$1.20 each',
    save: 'Save 20%',
    description: '5 downloads of any size. The everyday choice.',
    cta: 'Choose Pro',
    variant: 'outline',
  },
  {
    id: 'team',
    name: 'Team',
    credits: 10,
    price: '$9.99',
    perCredit: '$1.00 each',
    save: 'Save 33%',
    description: '10 downloads of any size. Best balance of price and volume.',
    cta: 'Choose Team',
    variant: 'solid',
    featured: true,
  },
  {
    id: 'studio',
    name: 'Studio',
    credits: 15,
    price: '$12.99',
    perCredit: '$0.87 each',
    save: 'Save 42% · best value',
    saveBest: true,
    description: '15 downloads of any size. Lowest price per file.',
    cta: 'Choose Studio',
    variant: 'solid',
  },
];

export const CONVERTER_SINGLE_DOWNLOAD_PRICE = '$1.50';
