export const MODEL_USE_OPTIONS = [
  { value: '', label: 'Select an option...' },
  { value: 'visualization-rendering', label: 'Visualization/rendering' },
  { value: 'cnc-machining-manufacturing', label: 'CNC machining/manufacturing' },
  { value: '3d-printing', label: '3D printing' },
  { value: 'prototyping', label: 'Prototyping' },
  { value: 'other', label: 'Other' },
]

export const SOFTWARE_FORMAT_OPTIONS = [
  { value: '', label: 'Select a software format...' },
  { value: 'SolidWorks', label: 'SolidWorks' },
  { value: 'Autodesk Fusion 360', label: 'Autodesk Fusion 360' },
  { value: 'AutoCAD', label: 'AutoCAD' },
  { value: 'CATIA', label: 'CATIA' },
  { value: 'Siemens NX', label: 'Siemens NX' },
  { value: 'PTC Creo', label: 'PTC Creo' },
  { value: 'Onshape', label: 'Onshape' },
  { value: 'FreeCAD', label: 'FreeCAD' },
  { value: 'Inventor', label: 'Inventor' },
  { value: 'Solid Edge', label: 'Solid Edge' },
  { value: 'Rhino', label: 'Rhino' },
  { value: 'Alibre Design', label: 'Alibre Design' },
  { value: 'TurboCAD', label: 'TurboCAD' },
  { value: 'BricsCAD', label: 'BricsCAD' },
  { value: 'T-FLEX CAD', label: 'T-FLEX CAD' },
  { value: 'ZW3D', label: 'ZW3D' },
  { value: 'IRONCAD', label: 'IRONCAD' },
  { value: 'Shapr3D', label: 'Shapr3D' },
  { value: 'OpenSCAD', label: 'OpenSCAD' },
  { value: 'VariCAD', label: 'VariCAD' },
  { value: 'CADKEY', label: 'CADKEY' },
  { value: 'DraftSight', label: 'DraftSight' },
  { value: 'NanoCAD', label: 'NanoCAD' },
  { value: 'ActCAD', label: 'ActCAD' },
  { value: 'Revit', label: 'Revit' },
  { value: 'ArchiCAD', label: 'ArchiCAD' },
  { value: 'SketchUp', label: 'SketchUp' },
  { value: 'Vectorworks', label: 'Vectorworks' },
  { value: 'Allplan', label: 'Allplan' },
  { value: 'Bentley MicroStation', label: 'Bentley MicroStation' },
  { value: 'Chief Architect', label: 'Chief Architect' },
  { value: 'Tekla Structures', label: 'Tekla Structures' },
  { value: 'Civil 3D', label: 'Civil 3D' },
  { value: 'STAAD.Pro', label: 'STAAD.Pro' },
  { value: 'Blender', label: 'Blender' },
  { value: 'Maya', label: 'Maya' },
  { value: '3ds Max', label: '3ds Max' },
  { value: 'Cinema 4D', label: 'Cinema 4D' },
  { value: 'Houdini', label: 'Houdini' },
  { value: 'ZBrush', label: 'ZBrush' },
  { value: 'Modo', label: 'Modo' },
  { value: 'LightWave 3D', label: 'LightWave 3D' },
  { value: 'Substance 3D Painter', label: 'Substance 3D Painter' },
  { value: 'Marvelous Designer', label: 'Marvelous Designer' },
  { value: 'DAZ Studio', label: 'DAZ Studio' },
  { value: 'Poser', label: 'Poser' },
  { value: 'Unity', label: 'Unity' },
  { value: 'Unreal Engine', label: 'Unreal Engine' },
  { value: 'Godot', label: 'Godot' },
  { value: 'CryEngine', label: 'CryEngine' },
  { value: 'V-Ray', label: 'V-Ray' },
  { value: 'Arnold', label: 'Arnold' },
  { value: 'KeyShot', label: 'KeyShot' },
  { value: 'Lumion', label: 'Lumion' },
  { value: 'Corona Renderer', label: 'Corona Renderer' },
  { value: 'Redshift', label: 'Redshift' },
  { value: 'OctaneRender', label: 'OctaneRender' },
  { value: 'Twinmotion', label: 'Twinmotion' },
  { value: 'Enscape', label: 'Enscape' },
  { value: 'Altium Designer', label: 'Altium Designer' },
  { value: 'KiCad', label: 'KiCad' },
  { value: 'Eagle', label: 'Eagle' },
  { value: 'OrCAD', label: 'OrCAD' },
  { value: 'Proteus', label: 'Proteus' },
  { value: 'ANSYS', label: 'ANSYS' },
  { value: 'COMSOL Multiphysics', label: 'COMSOL Multiphysics' },
  { value: 'Abaqus', label: 'Abaqus' },
  { value: 'HyperWorks', label: 'HyperWorks' },
  { value: 'OpenFOAM', label: 'OpenFOAM' },
  { value: 'MSC Nastran', label: 'MSC Nastran' },
  { value: 'LS-DYNA', label: 'LS-DYNA' },
  { value: 'Mastercam', label: 'Mastercam' },
  { value: 'PowerMill', label: 'PowerMill' },
  { value: 'Edgecam', label: 'Edgecam' },
  { value: 'Fusion 360 Manufacture', label: 'Fusion 360 Manufacture' },
  { value: 'SolidCAM', label: 'SolidCAM' },
  { value: 'HSMWorks', label: 'HSMWorks' },
  { value: 'Geomagic Design X', label: 'Geomagic Design X' },
  { value: 'MeshLab', label: 'MeshLab' },
  { value: 'RealityCapture', label: 'RealityCapture' },
  { value: 'Agisoft Metashape', label: 'Agisoft Metashape' },
  { value: 'Windchill', label: 'Windchill' },
  { value: 'Teamcenter', label: 'Teamcenter' },
  { value: '3DEXPERIENCE', label: '3DEXPERIENCE' },
  { value: 'Autodesk Vault', label: 'Autodesk Vault' },
  { value: 'Arena PLM', label: 'Arena PLM' },
  { value: 'OpenBOM', label: 'OpenBOM' },
]
